### ISSUE TITLE
Documentation needed: configuration file & dependency 'borgmatic'

### ISSUE THREAD

**Issue by thewilli** [danihodovic/borg-exporter#41]
I've came across this project when looking for a `borg` exporter. It took me some time to understand after some digging `borg` is not *directly* used or supported, but `borgmatic` seems to be used as some kind of *bridge* or *layer on top*.

While `borgmatic` is invoked to collect the information for the metrics, it seems to be not installed / required by this project as a (Python-) dependency.

Can you please clarify for those not into `borgmatic`

* what the dependencies are (or maybe try to install them as dependency, seems to be Python as well)
* how a minimal configuration looks like (or refer to some documentation of e.g. `borgmatic`)

Thanks!

**Comment by danihodovic** [comment]
Would you like to provide a PR since you're the first to bring up the confusing docs?
