### ISSUE TITLE
Multiple configurations

### ISSUE THREAD

**Issue by stoically** [danihodovic/borg-exporter#49]
Thanks for working on the borgmatic exporter!

It'd be great if the exporter service would support multiple configurations, unless I'm missing how they are already supported?

**Comment by danihodovic** [comment]
Thank you. What are multiple configurations?

**Comment by stoically** [comment]
Hm, I guess more accurate would be the question: Is it supported to export multiple repositories, based on their respective borgmatic configuration file?

**Comment by danihodovic** [comment]
To be honest with you I don't know. I wrote the program 15 months ago. Try it out and let me know!

**Comment by stoically** [comment]
Ah, it seems like https://github.com/danihodovic/borg-exporter/pull/27 added support. Thanks.

**Comment by danihodovic** [comment]
Clever contributor @R053NR07
