### ISSUE TITLE
Installation add systemd service but syntax error in file for borgmatic config path

### ISSUE THREAD

**Issue by PhilippeAccorsi** [danihodovic/borg-exporter#62]
Hi,

After installation of the last version, I have seen an error.
When I tried to start borg-exporter service, I saw this error
```
Feb 26 08:57:46 interne-11 systemd[1]: Started borg-exporter.service - Borg Prometheus exporter.
Feb 26 08:57:46 interne-11 borg-exporter[166834]: Usage: borg-exporter run [OPTIONS]
Feb 26 08:57:46 interne-11 borg-exporter[166834]: Try 'borg-exporter run --help' for help.
Feb 26 08:57:46 interne-11 borg-exporter[166834]: Error: Invalid value for '-c' / '--config': File '(/etc/borgmatic/config.yaml,)' does not exist.
```
The file exist in the path, so I tried to set `ExecStart` with this syntax and service start correctly (OS : Debian 12 bookworm)
```
ExecStart=/usr/local/bin/borg-exporter run --config '/etc/borgmatic/config.yaml'
```

After that, service is correctly started and I can seen metric on port 9996.

Question: what is the good way to change default port et ip address for listening ? Is it possible to set something like this `ExecStart=/usr/local/bin/borg-exporter run  --web.listen-address=0.0.0.0:9100 --config '/etc/borgmatic/config.yaml'` ? (I seen this in node_exporter)

Regards,

**Comment by danihodovic** [comment]
Yes, use --port

https://github.com/danihodovic/borg-exporter/blob/190947c78f7fc91cf8db7f4d3bfdf6c26c9dd406/src/cli.py#L39-L45
